apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      tier: front
      type: nodejs
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: voting-app
        tier: front
        type: nodejs
    spec:
      containers:
        - name: result-app-container
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
