apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      tier: front
      type: python
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: voting-app
        tier: front
        type: python
    spec:
      containers:
        - name: voting-app-container
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
      