apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      tier: backend
      type: worker
  template:
    metadata:
      name: worker-pod
      labels:
        app: voting-app
        tier: backend
        type: worker
    spec:
      containers:
        - name: worker-container
          image: kodekloud/examplevotingapp_worker:v1
          ports:
            - containerPort: 80