apiVersion: v1
kind: Service
metadata:
  name: service-4-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: voting-app
    tier: backend
    type: redis-db
