apiVersion: v1
kind: Service
metadata:
  name: service-4-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: voting-app
    tier: backend
    type: postgres-db
  