apiVersion: v1
kind: Service
metadata:
  name: get-to-result
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: voting-app
    tier: front
    type: nodejs
