apiVersion: v1
kind: Service
metadata:
  name: service-4-voting
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: voting-app
    tier: frontend
    type: python