apiVersion: v1
kind: Service
metadata:
  name: service-4-result
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: voting-app
    tier: frontend
    type: result
