apiVersion: v1
kind: Pod
metadata:
  name: redis-db-pod
  labels:
    app: voting-app
    tier: backend
    type: redis-db
spec:
  containers:
    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379
