apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: voting-app
    tier: front
    type: nodejs
spec:
  containers:
    - name: result-app-container
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80
