apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    app: voting-app
    tier: front
    type: nodesjs
spec:
  containers:
    - name: result-app-container
      image: kodekloud/examplevotingapp_result:v1
