apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    app: voting-app
    tier: front
    type: python
spec:
  containers:
    - name: voting-app-container
      image: kodekloud/examplevotingapp_vote:v1
