apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    app: voting-app
    tier: backend
spec:
  containers:
    - name: worker-container
      image: kodekloud/examplevotingapp_worker:v1
